services:
  shipped-agent:
    image: ghcr.io/tohjuler/shipped:latest
    restart: unless-stopped
    ports:
      - "5055:5055"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - db:/app/database
      - stacks:/stacks
    
volumes:
  db:
  stacks: