name: Backend - Test and Lint

on:
  push:
    paths:
      - 'Backend/**'
  pull_request:
    paths:
      - 'Backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: ./Backend
        run: bun install
      - name: Lint
        working-directory: ./Backend
        run: bun run lint 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: ./Backend
        run: bun install
      - name: Test
        working-directory: ./Backend
        run: bun run test
