name: Frontend - Lint

on:
  push:
    branches: ["main"]
    paths:
      - 'Frontend/**'
  pull_request:
    branches: ["main"]
    paths:
      - 'Frontend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: ./Frontend
        run: bun install
      - name: Lint
        working-directory: ./Frontend
        run: bun run lint
